load_defaults: 7.24.0
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/digitalwpi" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/digitalwpi" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_HOST'] %>
  #  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/digitalwpi" %>
